model_name: "flux-dev"

data_config:

  train_batch_size: 4      
  num_workers: 4           
  img_size: 512            
  images_dir: "/home/nishant/src/Datasets/images"
  maps_dir: "/home/nishant/src/Datasets/maps"
  contents_dir: "/home/nishant/src/Datasets/contents"

# Logging & reporting
report_to: wandb
tracker_project_name: "densepose_training"

# Training parameters
train_batch_size: 4       
output_dir: "saves_densepose"
max_train_steps: 100000
learning_rate: 2e-5
lr_scheduler: "constant"
lr_warmup_steps: 10
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0

mixed_precision: "bf16"

checkpointing_steps: 2500
checkpoints_total_limit: 10
resume_from_checkpoint: "latest"

gradient_accumulation_steps: 2

logging_dir: "logs"
